### PR TITLE
Fixed signal outputting and signal receiving

### LINKED ISSUE #6: in-game error: combinator behavior error
image

> ```
> The mod Moon Logic (0.0.83) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event Moon_Logic::on_tick (ID 0)
> LuaConstantCombinatorControlBehavior doesn't contain key signals_count.
> stack traceback:
> 	[C]: in function '__index'
> 	__Moon_Logic__/control.lua:290: in function 'mlc_update_output'
> 	__Moon_Logic__/control.lua:338: in function 'mlc_update_code'
> 	__Moon_Logic__/control.lua:463: in function 'mlc_init'
> 	__Moon_Logic__/control.lua:798: in function <__Moon_Logic__/control.lua:792>
> ```

Trace (Corrected):
- https://github.com/anonhostpi/mk-fg-games/blob/0778c1a9e0dfae86f561c571d78629258541ac64/factorio/Moon_Logic/control.lua#L265

### PR DESCRIPTION
**Pull request by chilla55**
fixes #6

### CODE REVIEW

File: factorio/Moon_Logic/control.lua [hunk 1]
```diff
@@ -262,17 +275,13 @@ local function mlc_update_output(mlc, output_raw)
 	for _, k in ipairs{'red', 'green'} do
 		ps, ecc = {}, mlc['out_'..k].get_or_create_control_behavior()
 		if not (ecc and ecc.valid) then goto skip end
-		n, n_max = 1, ecc.signals_count
+		n, n_max = 1, 1
```
Comment (anonhostpi) [inline factorio/Moon_Logic/control.lua]: This needs to be fixed. AFAIK, this max is no longer applicable.

From what I understand (which is not much lol), this would limit the amount of output signals to just 1, which is inconsistent with the new constant combinator, which can output all signals. I think, if you remove the n_max and the n_max check, this should work as originally intended.

Comment (anonhostpi) [reply factorio/Moon_Logic/control.lua]: I believe this was originally designed to be consistent with the old constant combinator behavior

**Review by anonhostpi — CHANGES_REQUESTED** [review]

File: factorio/Moon_Logic/control.lua (hunk 1 above)
Comment (chilla55) [reply factorio/Moon_Logic/control.lua]: i forgot to remove the variable and they completely removed the max number of signals per constant combinator

Comment (anonhostpi) [reply factorio/Moon_Logic/control.lua]: I read the diff wrong my bad. Have you tested it? Does it work or are you getting another error lol? If so, open another issue, and you can start work on another PR for it.

Comment (anonhostpi) [reply factorio/Moon_Logic/control.lua]: Bit busy working on a L4D2 server rn

Comment (chilla55) [reply factorio/Moon_Logic/control.lua]: As far as testing goes, I didn't find any other problems.
